In [1]:
import sqlite3
from sqlite3 import Error
import os
import pandas as pd
import numpy as np
import re

In [2]:
root_path = './'

In [3]:
root_path = './'
files = []
for root, _, file in os.walk(root_path):
    for f in file:
        if (os.path.splitext(f)[1] == ".csv"):
            file_path = os.path.join(root, f)
            activity = os.path.split(root)[-1]
            files.append(file_path)

In [4]:
folder = []
for i in files:
    a = i.split('/')
    folder.append(a[1])
folder

['Mental Health Dataset',
 'Mental Health Dataset',
 'Mental Health Dataset',
 'Mental Health Dataset',
 'Mental Health Dataset',
 'Mental Health Dataset',
 'Mental Health in Tech Survey',
 'Mental Health and Suicide Rates',
 'Mental Health and Suicide Rates',
 'Mental Health and Suicide Rates',
 'Mental Health and Suicide Rates',
 'World Happiness Report 2015-2021',
 'World Happiness Report 2015-2021',
 'World Happiness Report 2015-2021',
 'World Happiness Report 2015-2021',
 'World Happiness Report 2015-2021',
 'World Happiness Report 2015-2021',
 'World Happiness Report 2015-2021',
 'Life Expectancy (WHO)']

In [5]:
fn = []
for root, _, file in os.walk(root_path):
    for f in file:
        if (os.path.splitext(f)[1] == ".csv"):
            fn.append(f)

In [6]:
root

'./.ipynb_checkpoints'

In [7]:
for i in files:
    data_test = pd.read_csv(i)

In [8]:
Life_Expectancy_Data = pd.read_csv(files[0])
Mental_Health_Suicide_Rates_Age_standardized_suicide_rates = pd.read_csv(files[1])
Mental_Health_Suicide_Rates_Crude_suicide_rates = pd.read_csv(files[2])
Mental_Health_Suicide_Rates_Facilities = pd.read_csv(files[3])
Mental_Health_Suicide_Rates_Human_Resources = pd.read_csv(files[4])
Mental_Health_Dataset_mental_and_substance_use_as_share_of_disease = pd.read_csv(files[5])
Mental_Health_Dataset_prevalence_by_mental_and_substance_use_disorder = pd.read_csv(files[6])
Mental_Health_Dataset_prevalence_of_depression_males_vs_females = pd.read_csv(files[7])
Mental_Health_Dataset_share_with_depression = pd.read_csv(files[8])
Mental_Health_Dataset_share_with_mental_and_substance_disorders = pd.read_csv(files[9])
Mental_Health_Dataset_share_with_mental_or_substance_disorders_by_sex = pd.read_csv(files[10])
Mental_Health_Tech_Survey_survey = pd.read_csv(files[11])
World_Happiness_Report_2015_2021_2015 = pd.read_csv(files[12])
World_Happiness_Report_2015_2021_2016 = pd.read_csv(files[13])
World_Happiness_Report_2015_2021_2017 = pd.read_csv(files[14])
World_Happiness_Report_2015_2021_2018 = pd.read_csv(files[15])
World_Happiness_Report_2015_2021_2019 = pd.read_csv(files[16])
World_Happiness_Report_2015_2021_2020 = pd.read_csv(files[17])
World_Happiness_Report_2015_2021_2021 = pd.read_csv(files[18])

In [9]:
def create_connection(db_file):
    """ create a database connection to a SQLite database """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
    finally:
        if conn:
            conn.close()


if __name__ == '__main__':
    create_connection(r"./test.db")

2.6.0

In [10]:
conn = sqlite3.connect('./test.db')
cur = conn.cursor()
for i in files:
    casedf = pd.read_csv(i)
    #equal length partition
    casedf_p1 = casedf[:len(casedf)//3]
    casedf_p2 = casedf[len(casedf)//3:len(casedf)//3*2]
    casedf_p3 = casedf[len(casedf)//3*2:len(casedf)]
    
    file_name = i.split('/')[-1]
    file_name = file_name.split('.')[0]
    file_name = file_name.replace(' ','_')
    file_name_p1 = file_name + '_p1'
    file_name_p2 = file_name + '_p2'
    file_name_p3 = file_name + '_p3'
    
#     casedf_p1.to_csv(file_name_p1 + '.csv')
#     casedf_p2.to_csv(file_name_p2 + '.csv')
#     casedf_p3.to_csv(file_name_p3 + '.csv')
    
    casedf_p1.to_sql(file_name_p1, conn, if_exists='append', index = False)
    cur.close()
    casedf_p2.to_sql(file_name_p2, conn, if_exists='append', index = False)
    cur.close()
    casedf_p3.to_sql(file_name_p3, conn, if_exists='append', index = False)
    cur.close()

In [11]:
pd.read_sql('''SELECT * FROM Life_Expectancy_Data_p1''', conn)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,Gambia,2003,Developing,57.0,297.0,3,2.47,0.000000,94.0,119,...,87.0,4.22,87.0,2.7,NaN,NaN,9.6,9.6,0.395,7.3
975,Gambia,2002,Developing,56.6,298.0,3,2.08,0.000000,92.0,32,...,86.0,3.75,87.0,2.5,NaN,NaN,9.8,9.8,0.392,7.0
976,Gambia,2001,Developing,56.3,3.0,3,2.25,0.000000,91.0,99,...,85.0,3.71,87.0,2.3,NaN,NaN,1.0,1.0,0.384,6.8
977,Gambia,2000,Developing,55.9,33.0,3,2.18,0.000000,91.0,336,...,84.0,3.61,8.0,2.0,NaN,NaN,1.2,1.2,0.377,6.5
978,Georgia,2015,Developing,74.4,129.0,1,NaN,0.000000,94.0,431,...,91.0,NaN,94.0,0.1,3764.649120,37171.0,2.7,2.8,0.768,13.9

In [12]:
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
cur.execute('''SELECT name from sqlite_master where type= "table"''').fetchall()
cur.close()

In [13]:
name = pd.read_sql('''SELECT name from sqlite_master where type= "table"''', conn)
name

                                                 name
0   prevalence-by-mental-and-substance-use-disorde...
1   prevalence-by-mental-and-substance-use-disorde...
2   prevalence-by-mental-and-substance-use-disorde...
3        share-with-mental-and-substance-disorders_p1
4        share-with-mental-and-substance-disorders_p2
5        share-with-mental-and-substance-disorders_p3
6        prevalence-of-depression-males-vs-females_p1
7        prevalence-of-depression-males-vs-females_p2
8        prevalence-of-depression-males-vs-females_p3
9     mental-and-substance-use-as-share-of-disease_p1
10    mental-and-substance-use-as-share-of-disease_p2
11    mental-and-substance-use-as-share-of-disease_p3
12                           share-with-depression_p1
13                           share-with-depression_p2
14                           share-with-depression_p3
15  share-with-mental-or-substance-disorders-by-se...
16  share-with-mental-or-substance-disorders-by-se...
17  share-with-mental-or-substance-disorders-by-se...
18                                          survey_p1
19                                          survey_p2
20                                          survey_p3
21                             Crude_suicide_rates_p1
22                             Crude_suicide_rates_p2
23                             Crude_suicide_rates_p3
24                                      Facilities_p1
25                                      Facilities_p2
26                                      Facilities_p3
27                                 Human_Resources_p1
28                                 Human_Resources_p2
29                                 Human_Resources_p3
30                  Age-standardized_suicide_rates_p1
31                  Age-standardized_suicide_rates_p2
32                  Age-standardized_suicide_rates_p3
33                                            2020_p1
34                                            2020_p2
35                                            2020_p3
36                                            2021_p1
37                                            2021_p2
38                                            2021_p3
39                                            2019_p1
40                                            2019_p2
41                                            2019_p3
42                                            2018_p1
43                                            2018_p2
44                                            2018_p3
45                                            2015_p1
46                                            2015_p2
47                                            2015_p3
48                                            2016_p1
49                                            2016_p2
50                                            2016_p3
51                                            2017_p1
52                                            2017_p2
53                                            2017_p3
54                            Life_Expectancy_Data_p1
55                            Life_Expectancy_Data_p2
56                            Life_Expectancy_Data_p3

In [14]:
def create_table(conn, create_table_sql):
    """ create a table from the create_table_sql statement
    :param conn: Connection object
    :param create_table_sql: a CREATE TABLE statement
    :return:
    """
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)

In [15]:
def main():

    # create a database connection
    conn = sqlite3.connect('./test.db')
    sql_create_namenode_table = """ CREATE TABLE IF NOT EXISTS namenode (
                                        id integer PRIMARY KEY,
                                        location NOT NULL,
                                        name NOT NULL,
                                        type text NOT NULL
                                    ); """
    # create tables
    if conn is not None:
        # create projects table
        create_table(conn, sql_create_namenode_table)
if __name__ == '__main__':
    main()

In [16]:
j = 1
for i in fn:
    file_id = j
    file_location = './' + folder[j-1]
    file_type = 'FILE'
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
    sql = ''' INSERT INTO namenode(id,location,name,type)
              VALUES(?,?,?,?) '''
    namenode_info = (file_id,file_location,i,file_type)
    cur.execute(sql, namenode_info)
    conn.commit()
    cur.close()
    j = j + 1

In [17]:
file_name

'Life_Expectancy_Data'

In [18]:
pd.read_sql('''SELECT * from namenode''', conn)

,id,location,name,type
0,1,./Mental Health Dataset,prevalence-by-mental-and-substance-use-disorde...,FILE
1,2,./Mental Health Dataset,share-with-mental-and-substance-disorders.csv,FILE
2,3,./Mental Health Dataset,prevalence-of-depression-males-vs-females.csv,FILE
3,4,./Mental Health Dataset,mental-and-substance-use-as-share-of-disease.csv,FILE
4,5,./Mental Health Dataset,share-with-depression.csv,FILE
5,6,./Mental Health Dataset,share-with-mental-or-substance-disorders-by-se...,FILE
6,7,./Mental Health in Tech Survey,survey.csv,FILE
7,8,./Mental Health and Suicide Rates,Crude suicide rates.csv,FILE
8,9,./Mental Health and Suicide Rates,Facilities.csv,FILE
9,10,./Mental Health and Suicide Rates,Human Resources.csv,FILE
10,11,./Mental Health and Suicide Rates,Age-standardized suicide rates.csv,FILE
11,12,./World Happiness Report 2015-2021,2020.csv,FILE
12,13,./World Happiness Report 2015-2021,2021.csv,FILE
13,14,./World Happiness Report 2015-2021,2019.csv,FILE
14,15,./World Happiness Report 2015-2021,2018.csv,FILE
15,16,./World Happiness Report 2015-2021,2015.csv,FILE
16,17,./World Happiness Report 2015-2021,2016.csv,FILE
17,18,./World Happiness Report 2015-2021,2017.csv,FILE
18,19,./Life Expectancy (WHO),Life Expectancy Data.csv,FILE

In [19]:
distinct_folder = []
for x in folder:
    if x not in distinct_folder:
        distinct_folder.append(x)
for i in distinct_folder:
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
    sql = ''' INSERT INTO namenode(id,location,name,type)
              VALUES(?,?,?,?) '''
    namenode_info = (j,'./',i,'DIRECTORY')
    cur.execute(sql, namenode_info)
    conn.commit()
    cur.close()
    j = j + 1

In [20]:
pd.read_sql('''SELECT * from namenode''', conn)

,id,location,name,type
0,1,./Mental Health Dataset,prevalence-by-mental-and-substance-use-disorde...,FILE
1,2,./Mental Health Dataset,share-with-mental-and-substance-disorders.csv,FILE
2,3,./Mental Health Dataset,prevalence-of-depression-males-vs-females.csv,FILE
3,4,./Mental Health Dataset,mental-and-substance-use-as-share-of-disease.csv,FILE
4,5,./Mental Health Dataset,share-with-depression.csv,FILE
5,6,./Mental Health Dataset,share-with-mental-or-substance-disorders-by-se...,FILE
6,7,./Mental Health in Tech Survey,survey.csv,FILE
7,8,./Mental Health and Suicide Rates,Crude suicide rates.csv,FILE
8,9,./Mental Health and Suicide Rates,Facilities.csv,FILE
9,10,./Mental Health and Suicide Rates,Human Resources.csv,FILE
10,11,./Mental Health and Suicide Rates,Age-standardized suicide rates.csv,FILE
11,12,./World Happiness Report 2015-2021,2020.csv,FILE
12,13,./World Happiness Report 2015-2021,2021.csv,FILE
13,14,./World Happiness Report 2015-2021,2019.csv,FILE
14,15,./World Happiness Report 2015-2021,2018.csv,FILE
15,16,./World Happiness Report 2015-2021,2015.csv,FILE
16,17,./World Happiness Report 2015-2021,2016.csv,FILE
17,18,./World Happiness Report 2015-2021,2017.csv,FILE
18,19,./Life Expectancy (WHO),Life Expectancy Data.csv,FILE
19,20,./,Mental Health Dataset,DIRECTORY
20,21,./,Mental Health in Tech Survey,DIRECTORY
21,22,./,Mental Health and Suicide Rates,DIRECTORY
22,23,./,World Happiness Report 2015-2021,DIRECTORY
23,24,./,Life Expectancy (WHO),DIRECTORY

In [21]:
def mkdir(new_dir):
    a = new_dir.split(' ')
    b = []
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
    p = pd.read_sql('''SELECT * from namenode''', conn)
    p = len(p) + 1
    for i in a:
        k = i.split('/')
        b.append(k)
    for i in range(1,len(b[1])):
        direct = b[1][0] + '/'
        for j in range(1,i):
            direct = direct + b[1][j] + '/'
        sql = ''' INSERT INTO namenode(id,location,name,type)
                  VALUES(?,?,?,?) '''
        namenode_info = (p,direct,b[1][i],'DIRECTORY')
        cur.execute(sql, namenode_info)
        conn.commit()
        p = p + 1

In [22]:
mkdir('mkdir ./john/w/b')

In [23]:
p = pd.read_sql('''SELECT * from namenode''', conn)
p

,id,location,name,type
0,1,./Mental Health Dataset,prevalence-by-mental-and-substance-use-disorde...,FILE
1,2,./Mental Health Dataset,share-with-mental-and-substance-disorders.csv,FILE
2,3,./Mental Health Dataset,prevalence-of-depression-males-vs-females.csv,FILE
3,4,./Mental Health Dataset,mental-and-substance-use-as-share-of-disease.csv,FILE
4,5,./Mental Health Dataset,share-with-depression.csv,FILE
5,6,./Mental Health Dataset,share-with-mental-or-substance-disorders-by-se...,FILE
6,7,./Mental Health in Tech Survey,survey.csv,FILE
7,8,./Mental Health and Suicide Rates,Crude suicide rates.csv,FILE
8,9,./Mental Health and Suicide Rates,Facilities.csv,FILE
9,10,./Mental Health and Suicide Rates,Human Resources.csv,FILE
10,11,./Mental Health and Suicide Rates,Age-standardized suicide rates.csv,FILE
11,12,./World Happiness Report 2015-2021,2020.csv,FILE
12,13,./World Happiness Report 2015-2021,2021.csv,FILE
13,14,./World Happiness Report 2015-2021,2019.csv,FILE
14,15,./World Happiness Report 2015-2021,2018.csv,FILE
15,16,./World Happiness Report 2015-2021,2015.csv,FILE
16,17,./World Happiness Report 2015-2021,2016.csv,FILE
17,18,./World Happiness Report 2015-2021,2017.csv,FILE
18,19,./Life Expectancy (WHO),Life Expectancy Data.csv,FILE
19,20,./,Mental Health Dataset,DIRECTORY
20,21,./,Mental Health in Tech Survey,DIRECTORY
21,22,./,Mental Health and Suicide Rates,DIRECTORY
22,23,./,World Happiness Report 2015-2021,DIRECTORY
23,24,./,Life Expectancy (WHO),DIRECTORY
24,25,./,john,DIRECTORY
25,26,./john/,w,DIRECTORY
26,27,./john/w/,b,DIRECTORY

In [24]:
userinput = 'Life_Expectancy_Data_p1'
def getPartitionLocations(file):
    namenode_table = pd.read_sql('''SELECT * from namenode''', conn)
    a = file.split('_')
    index = 0
    for i in namenode_table['name']:
        b = i.split('.')[0]
        c = b.split(' ')
#         print(a)
#         print(c)
        if a[:-1] == c:
            print(namenode_table['location'][index])
        index = index + 1
        
getPartitionLocations(userinput)

./Life Expectancy (WHO)

In [25]:
userinput = 'Life Expectancy Data.csv'
def getPartitionLocations(file):
    namenode_table = pd.read_sql('''SELECT * from namenode''', conn)
    index = 0
    for i in namenode_table['name']:
        if i == file:
            print(namenode_table['location'][index])
    index = index + 1
getPartitionLocations(userinput)

./Mental Health Dataset

In [41]:
userinput1 = 'Life Expectancy Data.csv'
userinput2 = 3
def readPartition(file, partition):
    conn = sqlite3.connect('./test.db')
    namenode_table = pd.read_sql('''SELECT * from namenode''', conn)
    file = file.replace(' ', '_')
    file = file.split('.')[0]
    partition = str(partition)
    file = file + '_p' + partition
#     print(file)
    print(pd.read_sql('''SELECT * FROM '%s' ''' % file, conn))
readPartition(userinput1, userinput2)

      Country  Year      Status  Life expectancy   Adult Mortality  \
0       Palau  2013  Developing               NaN              NaN
1      Panama  2015  Developing              77.8            118.0
2      Panama  2014  Developing              77.6            119.0
3      Panama  2013  Developing              77.5            118.0
4      Panama  2012  Developing              77.2             12.0
..        ...   ...         ...               ...              ...
975  Zimbabwe  2004  Developing              44.3            723.0
976  Zimbabwe  2003  Developing              44.5            715.0
977  Zimbabwe  2002  Developing              44.8             73.0
978  Zimbabwe  2001  Developing              45.3            686.0
979  Zimbabwe  2000  Developing              46.0            665.0

     infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                0      NaN              344.690631         99.0         0
1                1      NaN                0.000000         73.0         0
2                1     6.74             1842.463782          8.0         0
3                1     6.89             1694.467075          8.0         0
4                1     6.95              201.749063         85.0         0
..             ...      ...                     ...          ...       ...
975             27     4.36                0.000000         68.0        31
976             26     4.06                0.000000          7.0       998
977             25     4.43                0.000000         73.0       304
978             25     1.72                0.000000         76.0       529
979             24     1.68                0.000000         79.0      1483

     ...  Polio  Total expenditure  Diphtheria    HIV/AIDS           GDP  \
0    ...   99.0               9.27         99.0        0.1   1932.122370
1    ...   72.0                NaN         73.0        0.1  13134.436700
2    ...    8.0               8.30          8.0        0.1  12593.737400
3    ...   81.0               8.90          8.0        0.1  11685.979830
4    ...   87.0               7.25         85.0        0.1   1589.827130
..   ...    ...                ...          ...        ...           ...
975  ...   67.0               7.13         65.0       33.6    454.366654
976  ...    7.0               6.52         68.0       36.7    453.351155
977  ...   73.0               6.53         71.0       39.8     57.348340
978  ...   76.0               6.16         75.0       42.1    548.587312
979  ...   78.0               7.10         78.0       43.5    547.358878

     Population   thinness  1-19 years   thinness 5-9 years  \
0         292.0                    0.1                  0.1
1     3969249.0                    1.9                  1.8
2      393986.0                    1.9                  1.8
3     3838462.0                    1.9                  1.9
4     3772938.0                    1.9                  1.9
..          ...                    ...                  ...
975  12777511.0                    9.4                  9.4
976  12633897.0                    9.8                  9.9
977    125525.0                    1.2                  1.3
978  12366165.0                    1.6                  1.7
979  12222251.0                   11.0                 11.2

     Income composition of resources  Schooling
0                              0.779       14.2
1                              0.785       13.0
2                              0.780       13.0
3                              0.773       12.9
4                              0.765       12.8
..                               ...        ...
975                            0.407        9.2
976                            0.418        9.5
977                            0.427       10.0
978                            0.427        9.8
979                            0.434        9.8

[980 rows x 22 columns]

In [27]:
def ls(dir_search):
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
    p = pd.read_sql('''SELECT * from namenode''', conn)
    a = dir_search.split('/')[2:]
    direct = "./"
    for i in a:
        direct = direct + i
    d = p[p["location"] == direct]
    ans = []
    for i in d['name']:
        ans.append(i)
    conn.commit()
    return ans

In [28]:
ls('ls/./Mental Health and Suicide Rates')

['Crude suicide rates.csv',
 'Facilities.csv',
 'Human Resources.csv',
 'Age-standardized suicide rates.csv']

In [33]:
def cat(file_name):
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
    a = file_name.split('/')[-1]
    a = a.replace(' ', '_')
    a = a.split('.')[0]
    df = pd.DataFrame()
    for i in range(1,4):
        file = a + '_p' + str(i)
        p = pd.read_sql('''SELECT * FROM '%s' ''' % file, conn)
        df = pd.concat([df,p])
    conn.commit()
    return df

In [34]:
cat('cat/./Mental Health and Suicide Rates/Crude suicide rates.csv')

,Country,Sex,80_above,70to79,60to69,50to59,40to49,30to39,20to29,10to19
0,Afghanistan,Both sexes,42.0,11.0,5.5,5.6,6.6,9.2,10.2,3.1
1,Afghanistan,Male,70.4,20.9,9.8,9.3,10.5,15.1,16.3,4.8
2,Afghanistan,Female,20.1,2.3,1.4,1.6,2.3,2.7,3.5,1.2
3,Albania,Both sexes,16.3,8.3,6.0,7.8,9.1,6.1,6.5,5.0
4,Albania,Male,23.2,11.9,8.1,11.4,13.5,8.8,6.3,3.1
...,...,...,...,...,...,...,...,...,...,...
178,Zambia,Male,152.1,79.0,38.7,27.3,17.0,13.3,12.3,3.9
179,Zambia,Female,31.2,26.4,16.0,11.2,6.9,4.6,4.2,1.6
180,Zimbabwe,Both sexes,205.7,81.5,41.3,29.4,19.2,13.7,11.3,4.6
181,Zimbabwe,Male,285.0,111.5,62.8,47.0,30.1,22.8,19.1,6.4
182,Zimbabwe,Female,152.4,59.4,26.4,16.0,9.4,5.5,3.8,2.7

In [35]:
p = pd.read_sql('''SELECT * from namenode''', conn)
p

,id,location,name,type
0,1,./Mental Health Dataset,prevalence-by-mental-and-substance-use-disorde...,FILE
1,2,./Mental Health Dataset,share-with-mental-and-substance-disorders.csv,FILE
2,3,./Mental Health Dataset,prevalence-of-depression-males-vs-females.csv,FILE
3,4,./Mental Health Dataset,mental-and-substance-use-as-share-of-disease.csv,FILE
4,5,./Mental Health Dataset,share-with-depression.csv,FILE
5,6,./Mental Health Dataset,share-with-mental-or-substance-disorders-by-se...,FILE
6,7,./Mental Health in Tech Survey,survey.csv,FILE
7,8,./Mental Health and Suicide Rates,Crude suicide rates.csv,FILE
8,9,./Mental Health and Suicide Rates,Facilities.csv,FILE
9,10,./Mental Health and Suicide Rates,Human Resources.csv,FILE
10,11,./Mental Health and Suicide Rates,Age-standardized suicide rates.csv,FILE
11,12,./World Happiness Report 2015-2021,2020.csv,FILE
12,13,./World Happiness Report 2015-2021,2021.csv,FILE
13,14,./World Happiness Report 2015-2021,2019.csv,FILE
14,15,./World Happiness Report 2015-2021,2018.csv,FILE
15,16,./World Happiness Report 2015-2021,2015.csv,FILE
16,17,./World Happiness Report 2015-2021,2016.csv,FILE
17,18,./World Happiness Report 2015-2021,2017.csv,FILE
18,19,./Life Expectancy (WHO),Life Expectancy Data.csv,FILE
19,20,./,Mental Health Dataset,DIRECTORY
20,21,./,Mental Health in Tech Survey,DIRECTORY
21,22,./,Mental Health and Suicide Rates,DIRECTORY
22,23,./,World Happiness Report 2015-2021,DIRECTORY
23,24,./,Life Expectancy (WHO),DIRECTORY
24,25,./,john,DIRECTORY
25,26,./john/,w,DIRECTORY
26,27,./john/w/,b,DIRECTORY

In [36]:
df2=p.query("name == 'survey.csv'")
p

,id,location,name,type
0,1,./Mental Health Dataset,prevalence-by-mental-and-substance-use-disorde...,FILE
1,2,./Mental Health Dataset,share-with-mental-and-substance-disorders.csv,FILE
2,3,./Mental Health Dataset,prevalence-of-depression-males-vs-females.csv,FILE
3,4,./Mental Health Dataset,mental-and-substance-use-as-share-of-disease.csv,FILE
4,5,./Mental Health Dataset,share-with-depression.csv,FILE
5,6,./Mental Health Dataset,share-with-mental-or-substance-disorders-by-se...,FILE
6,7,./Mental Health in Tech Survey,survey.csv,FILE
7,8,./Mental Health and Suicide Rates,Crude suicide rates.csv,FILE
8,9,./Mental Health and Suicide Rates,Facilities.csv,FILE
9,10,./Mental Health and Suicide Rates,Human Resources.csv,FILE
10,11,./Mental Health and Suicide Rates,Age-standardized suicide rates.csv,FILE
11,12,./World Happiness Report 2015-2021,2020.csv,FILE
12,13,./World Happiness Report 2015-2021,2021.csv,FILE
13,14,./World Happiness Report 2015-2021,2019.csv,FILE
14,15,./World Happiness Report 2015-2021,2018.csv,FILE
15,16,./World Happiness Report 2015-2021,2015.csv,FILE
16,17,./World Happiness Report 2015-2021,2016.csv,FILE
17,18,./World Happiness Report 2015-2021,2017.csv,FILE
18,19,./Life Expectancy (WHO),Life Expectancy Data.csv,FILE
19,20,./,Mental Health Dataset,DIRECTORY
20,21,./,Mental Health in Tech Survey,DIRECTORY
21,22,./,Mental Health and Suicide Rates,DIRECTORY
22,23,./,World Happiness Report 2015-2021,DIRECTORY
23,24,./,Life Expectancy (WHO),DIRECTORY
24,25,./,john,DIRECTORY
25,26,./john/,w,DIRECTORY
26,27,./john/w/,b,DIRECTORY

In [39]:
def rm(file_name):
    conn = sqlite3.connect('./test.db')
    cur = conn.cursor()
    a = file_name.split('/')[-1]
    p = pd.read_sql('''SELECT * from namenode''', conn)
    p = p.drop(p.index[p['name'] == a])
    conn.commit()
    return p

In [40]:
rm('./Mental Health and Suicide Rates/Facilities.csv')

,id,location,name,type
0,1,./Mental Health Dataset,prevalence-by-mental-and-substance-use-disorde...,FILE
1,2,./Mental Health Dataset,share-with-mental-and-substance-disorders.csv,FILE
2,3,./Mental Health Dataset,prevalence-of-depression-males-vs-females.csv,FILE
3,4,./Mental Health Dataset,mental-and-substance-use-as-share-of-disease.csv,FILE
4,5,./Mental Health Dataset,share-with-depression.csv,FILE
5,6,./Mental Health Dataset,share-with-mental-or-substance-disorders-by-se...,FILE
6,7,./Mental Health in Tech Survey,survey.csv,FILE
7,8,./Mental Health and Suicide Rates,Crude suicide rates.csv,FILE
9,10,./Mental Health and Suicide Rates,Human Resources.csv,FILE
10,11,./Mental Health and Suicide Rates,Age-standardized suicide rates.csv,FILE
11,12,./World Happiness Report 2015-2021,2020.csv,FILE
12,13,./World Happiness Report 2015-2021,2021.csv,FILE
13,14,./World Happiness Report 2015-2021,2019.csv,FILE
14,15,./World Happiness Report 2015-2021,2018.csv,FILE
15,16,./World Happiness Report 2015-2021,2015.csv,FILE
16,17,./World Happiness Report 2015-2021,2016.csv,FILE
17,18,./World Happiness Report 2015-2021,2017.csv,FILE
18,19,./Life Expectancy (WHO),Life Expectancy Data.csv,FILE
19,20,./,Mental Health Dataset,DIRECTORY
20,21,./,Mental Health in Tech Survey,DIRECTORY
21,22,./,Mental Health and Suicide Rates,DIRECTORY
22,23,./,World Happiness Report 2015-2021,DIRECTORY
23,24,./,Life Expectancy (WHO),DIRECTORY
24,25,./,john,DIRECTORY
25,26,./john/,w,DIRECTORY
26,27,./john/w/,b,DIRECTORY