In [20]:
import sqlite3
from sqlite3 import Error
import os
import pandas as pd
import numpy as np
import re

In [21]:
root_path = './'

In [22]:
root_path = './'
files = []
for root, _, file in os.walk(root_path):
    for f in file:
        if (os.path.splitext(f)[1] == ".csv"):
            file_path = os.path.join(root, f)
            activity = os.path.split(root)[-1]
            files.append(file_path)

In [23]:
for root, _, file in os.walk(root_path):
    for f in file:
        if (os.path.splitext(f)[1] == ".csv"):
            print(f)

Age-standardized suicide rates_p1.csv
Age-standardized suicide rates_p2.csv
Age-standardized suicide rates_p3.csv
share-with-mental-and-substance-disorders_p2.csv
share-with-mental-and-substance-disorders_p3.csv
share-with-mental-and-substance-disorders_p1.csv
prevalence-by-mental-and-substance-use-disorder_p2.csv
share-with-mental-or-substance-disorders-by-sex_p1.csv
2018_p1.csv
prevalence-by-mental-and-substance-use-disorder_p3.csv
prevalence-by-mental-and-substance-use-disorder_p1.csv
2018_p3.csv
share-with-mental-or-substance-disorders-by-sex_p2.csv
share-with-mental-or-substance-disorders-by-sex_p3.csv
2018_p2.csv
2020_p2.csv
2016_p3.csv
survey_p2.csv
survey_p3.csv
2016_p2.csv
2020_p3.csv
2020_p1.csv
survey_p1.csv
2016_p1.csv
prevalence-of-depression-males-vs-females_p2.csv
Human Resources_p3.csv
mental-and-substance-use-as-share-of-disease_p1.csv
Human Resources_p2.csv
prevalence-of-depression-males-vs-females_p3.csv
prevalence-of-depression-males-vs-females_p1.csv
mental-and-substance-use-as-share-of-disease_p2.csv
mental-and-substance-use-as-share-of-disease_p3.csv
Human Resources_p1.csv
2015_p2.csv
2019_p2.csv
2019_p3.csv
Crude suicide rates_p1.csv
2015_p3.csv
2015_p1.csv
Crude suicide rates_p3.csv
2019_p1.csv
Crude suicide rates_p2.csv
Life Expectancy Data_p1.csv
share-with-depression_p3.csv
Facilities_p2.csv
2017_p1.csv
2021_p1.csv
Facilities_p3.csv
share-with-depression_p2.csv
Life Expectancy Data_p2.csv
Facilities_p1.csv
2021_p3.csv
2017_p2.csv
2017_p3.csv
2021_p2.csv
share-with-depression_p1.csv
Life Expectancy Data_p3.csv
prevalence-by-mental-and-substance-use-disorder.csv
share-with-mental-and-substance-disorders.csv
prevalence-of-depression-males-vs-females.csv
mental-and-substance-use-as-share-of-disease.csv
share-with-depression.csv
share-with-mental-or-substance-disorders-by-sex.csv
survey.csv
Crude suicide rates.csv
Facilities.csv
Human Resources.csv
Age-standardized suicide rates.csv
2020.csv
2021.csv
2019.csv
2018.csv
2015.csv
2016.csv
2017.csv
Life Expectancy Data.csv

In [24]:
files

['./Age-standardized suicide rates_p1.csv',
 './Age-standardized suicide rates_p2.csv',
 './Age-standardized suicide rates_p3.csv',
 './share-with-mental-and-substance-disorders_p2.csv',
 './share-with-mental-and-substance-disorders_p3.csv',
 './share-with-mental-and-substance-disorders_p1.csv',
 './prevalence-by-mental-and-substance-use-disorder_p2.csv',
 './share-with-mental-or-substance-disorders-by-sex_p1.csv',
 './2018_p1.csv',
 './prevalence-by-mental-and-substance-use-disorder_p3.csv',
 './prevalence-by-mental-and-substance-use-disorder_p1.csv',
 './2018_p3.csv',
 './share-with-mental-or-substance-disorders-by-sex_p2.csv',
 './share-with-mental-or-substance-disorders-by-sex_p3.csv',
 './2018_p2.csv',
 './2020_p2.csv',
 './2016_p3.csv',
 './survey_p2.csv',
 './survey_p3.csv',
 './2016_p2.csv',
 './2020_p3.csv',
 './2020_p1.csv',
 './survey_p1.csv',
 './2016_p1.csv',
 './prevalence-of-depression-males-vs-females_p2.csv',
 './Human Resources_p3.csv',
 './mental-and-substance-use-as-share-of-disease_p1.csv',
 './Human Resources_p2.csv',
 './prevalence-of-depression-males-vs-females_p3.csv',
 './prevalence-of-depression-males-vs-females_p1.csv',
 './mental-and-substance-use-as-share-of-disease_p2.csv',
 './mental-and-substance-use-as-share-of-disease_p3.csv',
 './Human Resources_p1.csv',
 './2015_p2.csv',
 './2019_p2.csv',
 './2019_p3.csv',
 './Crude suicide rates_p1.csv',
 './2015_p3.csv',
 './2015_p1.csv',
 './Crude suicide rates_p3.csv',
 './2019_p1.csv',
 './Crude suicide rates_p2.csv',
 './Life Expectancy Data_p1.csv',
 './share-with-depression_p3.csv',
 './Facilities_p2.csv',
 './2017_p1.csv',
 './2021_p1.csv',
 './Facilities_p3.csv',
 './share-with-depression_p2.csv',
 './Life Expectancy Data_p2.csv',
 './Facilities_p1.csv',
 './2021_p3.csv',
 './2017_p2.csv',
 './2017_p3.csv',
 './2021_p2.csv',
 './share-with-depression_p1.csv',
 './Life Expectancy Data_p3.csv',
 './Mental Health Dataset/prevalence-by-mental-and-substance-use-disorder.csv',
 './Mental Health Dataset/share-with-mental-and-substance-disorders.csv',
 './Mental Health Dataset/prevalence-of-depression-males-vs-females.csv',
 './Mental Health Dataset/mental-and-substance-use-as-share-of-disease.csv',
 './Mental Health Dataset/share-with-depression.csv',
 './Mental Health Dataset/share-with-mental-or-substance-disorders-by-sex.csv',
 './Mental Health in Tech Survey/survey.csv',
 './Mental Health and Suicide Rates/Crude suicide rates.csv',
 './Mental Health and Suicide Rates/Facilities.csv',
 './Mental Health and Suicide Rates/Human Resources.csv',
 './Mental Health and Suicide Rates/Age-standardized suicide rates.csv',
 './World Happiness Report 2015-2021/2020.csv',
 './World Happiness Report 2015-2021/2021.csv',
 './World Happiness Report 2015-2021/2019.csv',
 './World Happiness Report 2015-2021/2018.csv',
 './World Happiness Report 2015-2021/2015.csv',
 './World Happiness Report 2015-2021/2016.csv',
 './World Happiness Report 2015-2021/2017.csv',
 './Life Expectancy (WHO)/Life Expectancy Data.csv']

In [25]:
for i in files:
    data_test = pd.read_csv(i)

In [26]:
Life_Expectancy_Data = pd.read_csv(files[0])
Mental_Health_Suicide_Rates_Age_standardized_suicide_rates = pd.read_csv(files[1])
Mental_Health_Suicide_Rates_Crude_suicide_rates = pd.read_csv(files[2])
Mental_Health_Suicide_Rates_Facilities = pd.read_csv(files[3])
Mental_Health_Suicide_Rates_Human_Resources = pd.read_csv(files[4])
Mental_Health_Dataset_mental_and_substance_use_as_share_of_disease = pd.read_csv(files[5])
Mental_Health_Dataset_prevalence_by_mental_and_substance_use_disorder = pd.read_csv(files[6])
Mental_Health_Dataset_prevalence_of_depression_males_vs_females = pd.read_csv(files[7])
Mental_Health_Dataset_share_with_depression = pd.read_csv(files[8])
Mental_Health_Dataset_share_with_mental_and_substance_disorders = pd.read_csv(files[9])
Mental_Health_Dataset_share_with_mental_or_substance_disorders_by_sex = pd.read_csv(files[10])
Mental_Health_Tech_Survey_survey = pd.read_csv(files[11])
World_Happiness_Report_2015_2021_2015 = pd.read_csv(files[12])
World_Happiness_Report_2015_2021_2016 = pd.read_csv(files[13])
World_Happiness_Report_2015_2021_2017 = pd.read_csv(files[14])
World_Happiness_Report_2015_2021_2018 = pd.read_csv(files[15])
World_Happiness_Report_2015_2021_2019 = pd.read_csv(files[16])
World_Happiness_Report_2015_2021_2020 = pd.read_csv(files[17])
World_Happiness_Report_2015_2021_2021 = pd.read_csv(files[18])

In [27]:
World_Happiness_Report_2015_2021_2021

,Unnamed: 0,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,838,2014-08-28 16:42:49,43,m,United Kingdom,NaN,No,Yes,No,NaN,...,Very easy,Maybe,No,Some of them,Yes,No,Maybe,Don't know,No,NaN
1,839,2014-08-28 16:52:23,36,M,United States,PA,No,No,No,Rarely,...,Somewhat difficult,No,No,Some of them,Yes,No,No,No,No,NaN
2,840,2014-08-28 16:52:34,43,male,United States,GA,No,No,Yes,Sometimes,...,Very difficult,Maybe,No,Some of them,Yes,No,No,Don't know,No,NaN
3,841,2014-08-28 16:52:34,36,male,United Kingdom,NaN,Yes,No,No,Sometimes,...,Somewhat difficult,No,No,Yes,Yes,No,Maybe,Don't know,Yes,NaN
4,842,2014-08-28 16:54:49,31,Female,United States,NY,No,Yes,Yes,Sometimes,...,Somewhat difficult,No,No,Yes,Yes,Maybe,Maybe,Don't know,No,I have been incredibly public about my own str...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
417,1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
418,1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
419,1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
420,1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [28]:
# def create_connection(db_file):
#     """ create a database connection to a SQLite database """
#     conn = None
#     try:
#         conn = sqlite3.connect(db_file)
#         print(sqlite3.version)
#     except Error as e:
#         print(e)
#     finally:
#         if conn:
#             conn.close()


# if __name__ == '__main__':
#      create_connection(r"./pythonsqlite.db")

In [29]:
# cur = conn.cursor()
# cur.execute('''SELECT * FROM Life_Expectancy_Data''').fetchall()

In [30]:
# pd.read_sql('''SELECT * FROM Life_Expectancy_Data''', conn)

In [31]:
# pd.read_sql('''SELECT * FROM Life_Expectancy_Data PARTITION BY HASH(Country) PARTITIONS 4''', conn)

In [32]:
# len(Life_Expectancy_Data)//3

In [33]:
# Life_Expectancy_Data[:len(Life_Expectancy_Data)//3]

In [34]:
# Life_Expectancy_Data[len(Life_Expectancy_Data)//3:len(Life_Expectancy_Data)//3*2]

In [35]:
# Life_Expectancy_Data[len(Life_Expectancy_Data)//3*2:len(Life_Expectancy_Data)]

In [39]:
def create_connection(db_file):
    """ create a database connection to a SQLite database """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
    finally:
        if conn:
            conn.close()


if __name__ == '__main__':
    create_connection(r"./test.db")

2.6.0

In [37]:
# conn = sqlite3.connect('./test.db')
# cur = conn.cursor()
# Life_Expectancy_Data.to_sql('Life_Expectancy_Data', conn, if_exists='append', index = False)
# # conn.commit()
# cur.close()

In [42]:
files

['./Age-standardized suicide rates_p1.csv',
 './Age-standardized suicide rates_p2.csv',
 './Age-standardized suicide rates_p3.csv',
 './share-with-mental-and-substance-disorders_p2.csv',
 './share-with-mental-and-substance-disorders_p3.csv',
 './share-with-mental-and-substance-disorders_p1.csv',
 './prevalence-by-mental-and-substance-use-disorder_p2.csv',
 './share-with-mental-or-substance-disorders-by-sex_p1.csv',
 './2018_p1.csv',
 './prevalence-by-mental-and-substance-use-disorder_p3.csv',
 './prevalence-by-mental-and-substance-use-disorder_p1.csv',
 './2018_p3.csv',
 './share-with-mental-or-substance-disorders-by-sex_p2.csv',
 './share-with-mental-or-substance-disorders-by-sex_p3.csv',
 './2018_p2.csv',
 './2020_p2.csv',
 './2016_p3.csv',
 './survey_p2.csv',
 './survey_p3.csv',
 './2016_p2.csv',
 './2020_p3.csv',
 './2020_p1.csv',
 './survey_p1.csv',
 './2016_p1.csv',
 './prevalence-of-depression-males-vs-females_p2.csv',
 './Human Resources_p3.csv',
 './mental-and-substance-use-as-share-of-disease_p1.csv',
 './Human Resources_p2.csv',
 './prevalence-of-depression-males-vs-females_p3.csv',
 './prevalence-of-depression-males-vs-females_p1.csv',
 './mental-and-substance-use-as-share-of-disease_p2.csv',
 './mental-and-substance-use-as-share-of-disease_p3.csv',
 './Human Resources_p1.csv',
 './2015_p2.csv',
 './2019_p2.csv',
 './2019_p3.csv',
 './Crude suicide rates_p1.csv',
 './2015_p3.csv',
 './2015_p1.csv',
 './Crude suicide rates_p3.csv',
 './2019_p1.csv',
 './Crude suicide rates_p2.csv',
 './Life Expectancy Data_p1.csv',
 './share-with-depression_p3.csv',
 './Facilities_p2.csv',
 './2017_p1.csv',
 './2021_p1.csv',
 './Facilities_p3.csv',
 './share-with-depression_p2.csv',
 './Life Expectancy Data_p2.csv',
 './Facilities_p1.csv',
 './2021_p3.csv',
 './2017_p2.csv',
 './2017_p3.csv',
 './2021_p2.csv',
 './share-with-depression_p1.csv',
 './Life Expectancy Data_p3.csv',
 './Mental Health Dataset/prevalence-by-mental-and-substance-use-disorder.csv',
 './Mental Health Dataset/share-with-mental-and-substance-disorders.csv',
 './Mental Health Dataset/prevalence-of-depression-males-vs-females.csv',
 './Mental Health Dataset/mental-and-substance-use-as-share-of-disease.csv',
 './Mental Health Dataset/share-with-depression.csv',
 './Mental Health Dataset/share-with-mental-or-substance-disorders-by-sex.csv',
 './Mental Health in Tech Survey/survey.csv',
 './Mental Health and Suicide Rates/Crude suicide rates.csv',
 './Mental Health and Suicide Rates/Facilities.csv',
 './Mental Health and Suicide Rates/Human Resources.csv',
 './Mental Health and Suicide Rates/Age-standardized suicide rates.csv',
 './World Happiness Report 2015-2021/2020.csv',
 './World Happiness Report 2015-2021/2021.csv',
 './World Happiness Report 2015-2021/2019.csv',
 './World Happiness Report 2015-2021/2018.csv',
 './World Happiness Report 2015-2021/2015.csv',
 './World Happiness Report 2015-2021/2016.csv',
 './World Happiness Report 2015-2021/2017.csv',
 './Life Expectancy (WHO)/Life Expectancy Data.csv']

In [40]:
conn = sqlite3.connect('./test.db')
cur = conn.cursor()
for i in files:
    casedf = pd.read_csv(i)
    #equal length partition
    casedf_p1 = casedf[:len(casedf)//3]
    casedf_p2 = casedf[len(casedf)//3:len(casedf)//3*2]
    casedf_p3 = casedf[len(casedf)//3*2:len(casedf)]
    
    file_name = i.split('\\')[-1]
    file_name = file_name.split('.')[0]
    file_name_p1 = file_name + '_p1'
    file_name_p2 = file_name + '_p2'
    file_name_p3 = file_name + '_p3'
    
#     casedf_p1.to_csv(file_name_p1 + '.csv')
#     casedf_p2.to_csv(file_name_p2 + '.csv')
#     casedf_p3.to_csv(file_name_p3 + '.csv')
    
    casedf_p1.to_sql(file_name_p1, conn, if_exists='append', index = False)
    cur.close()
    casedf_p2.to_sql(file_name_p2, conn, if_exists='append', index = False)
    cur.close()
    casedf_p3.to_sql(file_name_p3, conn, if_exists='append', index = False)
    cur.close()

OperationalError: table _p1 has no column named Entity

In [ ]:
pd.read_sql('''SELECT * FROM survey_p2''', conn)

In [ ]:
conn = sqlite3.connect('./test.db')
cur = conn.cursor()
cur.execute('''SELECT name from sqlite_master where type= "table"''').fetchall()
cur.close()

In [ ]:
pd.read_sql('''SELECT name from sqlite_master where type= "table"''', conn)

In [ ]:
for i in files:
#     print(os.path.splitext(i))
#     print（i）
    x = i.split('\\')[-1]
    x = x.split('.')[0]
    print(x)